project_id = "mypjtbbwhyztnuhuczei"

[auth]
  [auth.email]
    [auth.email.template]
      [auth.email.template.confirmation]
        content_path = "./templates/confirmation.html"
        subject = "Confirm your email - CarbonTrack"
      [auth.email.template.magic_link]
        content_path = "./templates/magic_link.html"
        subject = "Your login link - CarbonTrack"
      [auth.email.template.recovery]
        content_path = "./templates/recovery.html"
        subject = "Reset your password - CarbonTrack"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.register-user]
    verify_jwt = false
